### ISSUE TITLE
validate failed

### ISSUE THREAD

**Issue by ozbillwang** [terraform-community-modules/tf_aws_ecs#10]
>$ terraform validate
>Error loading files Error loading github/terraform-community-modules/tf_aws_ecs/main.tf: Error reading config for aws_launch_configuration[ecs]: parse error at 1:10: expected expression but found "["

>$ terraform version
>Terraform v0.9.11

Release `tags/v2.0.0` is fine. Problem is between `v2.0.0` and `v2.1.0`

**Comment by ozbillwang** [comment]
Problem is at this line:

      security_groups             = "${concat([aws_security_group.ecs.id], var.security_group_ids)}"

After commented it, validate is fine.

**Comment by ozbillwang** [comment]
Ok, I will raise PR if the original PRer doesn't fix it (https://github.com/terraform-community-modules/tf_aws_ecs/pull/9#pullrequestreview-52567490) and add a function (PR #11) to validate the codes automatically when merge to master branch (via travis.ci)

**Comment by tfhartmann** [comment]
This is a great idea, and something we should have added sooner, I'd prefer CircleCI though, mostly because it's what I'm using for a number of other projects already.

**Comment by tfhartmann** [comment]
@antonbabenko do you have any particular feelings either way?

**Comment by antonbabenko** [comment]
@ozbillwang Thank you for the code.

@tfhartmann I am a big fan of CircleCI (especially features which are available in 2.0). I have been using it for a couple years and very happy for both private and public projects. Before I left on vacation (where I am still right now, ¡Hola 🇪🇸 ! ) I have started [terrapin](https://github.com/antonbabenko/terrapin) where CircleCI 2.0 is used and I am very glad about it. Check [official CircleCI 2.0 docs](https://circleci.com/docs/2.0/) to learn more about it.

I would like us to use CircleCI 2.0 for this Terraform module, and luckily TravisCI and CircleCI are rather compatible, so it should be fairly straightforward to start using it here.

**Comment by ozbillwang** [comment]
@tfhartmann & @antonbabenko 

Are you going to revert the PR (#9) or not? Currently, this repo can't be used at all.

**Comment by ozbillwang** [comment]
Ok, someone has raised the PR #12 and fix this issue. 

This ticket can be closed now.
