### ISSUE TITLE
Consistent resource naming convetions

### ISSUE THREAD

**Issue by watchwithmike** [terraform-community-modules/tf_aws_ecs#28]
The [iam.tf](https://github.com/terraform-community-modules/tf_aws_ecs/blob/master/iam.tf) file contains two different resource naming conventions:

The `ecs_profile` resource uses underscores while all other resource names use hyphens (e.g. `ecs-role`, `ecs-policy`, etc...).

Can a consistent convention be used throughout?  It appears that underscores `_` are more common.  Happy to submit a pull request if that's the desired approach.

Cheers,
Mike

https://github.com/terraform-community-modules/tf_aws_ecs/blob/f7af3a030f8ac3702340e9e2f4d85fd227b2c576/iam.tf#L1-L7

**Comment by hakamadare** [comment]
@watchwithmike done!  i've tagged this as v5.0.0 because i haven't verified that the rename is nondisruptive, please lmk whether you run into trouble with this.

PRs are always welcome, but this was pretty straightforward :)
