### ISSUE TITLE
ECS Instance Draining on scale in

### ISSUE THREAD

**Issue by tfhartmann** [terraform-community-modules/tf_aws_ecs#4]
This module might benefit from adding this module  terraform-community-modules/tf_aws_ecs_instance_draining_on_scale_in as a dependency. Not sure though yet if this is desirable  or not...

**Comment by antonbabenko** [comment]
I think if someone want to use both of these modules they can do this as long as dependant values are in `outputs`. There can be code sample showing this optional integration.
