### ISSUE TITLE
Allow enabling metrics and output roles

### ISSUE THREAD

**Issue by Stretch96** [terraform-community-modules/tf_aws_ecs#44]
Hello 👋 

I opened a couple of PRs a few months ago, wondering if they're okay to get merged in or if there's outstanding work required for them to be accepted

Could be my bad for not opening a related issue.

The PRs are:

https://github.com/terraform-community-modules/tf_aws_ecs/pull/39
https://github.com/terraform-community-modules/tf_aws_ecs/pull/38

Thanks,
Chris

**Comment by tfhartmann** [comment]
Hi! I think they just fell off my inbox. 😄  I'll take a look at em!

**Comment by tfhartmann** [comment]
Merged! I'll cut a new release shortly!

**Comment by Stretch96** [comment]
Awesome thanks, got one more too that I'm just rebasing 😬 ... https://github.com/terraform-community-modules/tf_aws_ecs/pull/45

**Comment by Stretch96** [comment]
It's good to go now 👍
