### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by Stretch96** [terraform-community-modules/tf_aws_ecs#47]
Hi 👋 

Could we get a release tag added due to the recently merged PR's?

Thanks 😬

**Comment by Stretch96** [comment]
Actually, my last rebase messed up the README a little, I'll open a fix for that first ...

**Comment by Stretch96** [comment]
Fix: https://github.com/terraform-community-modules/tf_aws_ecs/pull/48

**Comment by tfhartmann** [comment]
v.5.6.0 released!

**Comment by Stretch96** [comment]
Awesome thanks 👍
