### ISSUE TITLE
[BUG] broken docker configuration on amzn2 ECS image

### ISSUE THREAD

**Issue by hogarth-sv** [terraform-community-modules/tf_aws_ecs#58]
The user_data.tpl template appends the following line to /etc/sysconfig/docker:
```
echo 'OPTIONS="$${OPTIONS} --storage-opt dm.basesize=${docker_storage_size}G"' >> /etc/sysconfig/docker
```

The amzn2 ECS images use a proper systemd unit to start docker instead of a sysvinit script.

The /etc/sysconfig/docker file is referenced for environment variables but the file isn't sourced, as in the way the sysvinit scripts work, so that appended line doesn't result in the OPTIONS envvar being built up, but rather being set to that. This then causes the docker service to fail on reboot of the instance or restart of the service with the error "dockerd accepts no arguments".

This is not noticed normally because the next line in the template `/etc/init.d/docker restart` is invalid in the amzn2 systemd instances so it doesn't actually restart docker and encounter this broken config .... you only get caught out by it on a service restart or a reboot.

In our use of this module we're now doing a `sed -i '/OPTIONS="${OPTIONS}/d' /etc/sysconfig/docker` to avoid this particular problem.

**Comment by ibrahima** [comment]
I found this via Google for a related issue, and this was helpful, so I just wanted to add a few things.

- Amazon Linux 2 uses OverlayFS, not devicemapper, so setting `dm.basesize` won't have an effect and/or might raise an error. If you don't need to set a maximum size per container, then [you might not need to fiddle with this anyway](https://github.com/aws/containers-roadmap/issues/526#issuecomment-820989324). I think with devicemapper [you needed to set this to increase the max from 10GB](https://docs.docker.com/engine/reference/commandline/dockerd/#dmbasesize).
- In the overlay2 storage driver the similar option for setting a max size per container is [`overlay2.size`](https://docs.docker.com/engine/reference/commandline/dockerd/#overlay2size).

(I'm not actually using this module at all, but I ran into a similar issue and wanted to clarify these points for anyone else who comes across this.)

**Comment by antonbabenko** [comment]
Please consider using a much more up-to-date and maintained Terraform AWS module for ECS - https://github.com/terraform-aws-modules/terraform-aws-ecs

PS: We need to wait a few more days to get through this PR - https://github.com/terraform-aws-modules/terraform-aws-ecs/pull/76

PPS: This module is not maintained anymore.
