### ISSUE TITLE
When a cluster is connected to a non-default VPC, its instances won't have internet access by default.

### ISSUE THREAD

**Issue by jasiek** [terraform-community-modules/tf_aws_ecs#6]
Cluster will show up as not having any instances. Is there a way to display a warning to a user stating that this may happen? Perhaps a dependency via a `data.aws_internet_gateway` dependency (this currently does not appear to be exposed via terraform)?

**Comment by jasiek** [comment]
This is due to instances not being able to connect to the ECS broker, which has a public IPv4 address.

**Comment by tfhartmann** [comment]
@jasiek are your instances on private networks not able to reach the internet at all? For example, using a NAT Gateway to allow private networks to route outbound traffic.

**Comment by jasiek** [comment]
Yes - adding a NAT would resolve this. My motivation for this request was to warn the user that this might happen, as I've found myself in this situation multiple times.
